#!/bin/bash

# Build docker image
git clone https://github.com/zdk/dokku-pg-dockerfiles /tmp/dokku-pg-dockerfiles
docker build -q=true -t zdkaster/postgresql /tmp/dokku-pg-dockerfiles
rm -rf /tmp/dokku-pg-dockerfiles
